- include_vars: zmienne.yaml
- name: Nowy kontener
community.general.proxmox:
  node: proxmox
  api_user: root@pam
  api_password: Belinea03
  api_host: 192.168.1.137
  password: Superhaslo5
  hostname: {{ item.hostname }}
  ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
  storage: local-lvm
  netif: '{"net0":"name=eth0,gw=192.168.1.1,ip={{ item.adresIP }}/24,bridge=vmbr0"}'
loop: "{{ ustawienia }}"    