- name: Uruchom kontener
  community.general.proxmox:
    hostname: "{{ item.hostname }}"
    api_user: root@pam
    api_password: Belinea03
    api_host: 192.168.1.137
    state: started
  loop: "{{ ustawienia }}"
