apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # volumes:
      # - name: cfg
      #   secret:
      #     secretName: mysecret
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MY_ENV
          value: test-me
        - name: TEST
          valueFrom:
            secretKeyRef:
              key: test
              name: mysecret
        # volumeMounts:
        # - name: cfg
        #   mountPath: /tmp
