apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer
  labels:
    name: pc
spec:
  containers:
  - name: producer
    image: ubuntu
    command:
    - "/bin/bash"
    - "-c"
    args:
    - while true; do
        date > /html/index.html;
        sleep 1;
      done
    volumeMounts:
    - name: data
      mountPath: /html
  - name: consumer
    image: httpd
    volumeMounts:
    - name: data
      mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: data
    emptyDir: {}
