---
 # Instalacja Zabbix Agent i edycja pliku konfiguracyjnego Zabbix Agenta
 # nano /etc/zabbix_agentd.conf - plik konfiguracyjny zabbix
 - hosts: all
   become: True
   tasks:
    - name: Instalacja Zabbix Agenta
      dnf:
        name: https://repo.zabbix.com/zabbix/6.5/centos/9/x86_64/zabbix-agent-7.0.0-alpha3.release1.el9.x86_64.rpm
        state: present
        disable_gpg_check: yes
    # - name: Dodanie EnableCommands
    #   lineinfile:
    #    path: /etc/zabbix_agentd.conf
    #    insertbefore: '### Option: LogRemoteCommands'
    #    line: 'EnableRemoteCommands=0'
    #    backup: yes
    - name: Zamiana EnableRemoteCommands=0
      replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: 'EnableRemoteCommands=0'
       replace: '# EnableRemoteCommands=0'
       backup: yes
    - name: Zmiana IP
      replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: 'Server=127.0.0.1'
       replace: 'Server=192.168.168.145'
    - name: Zmiana portu
      replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '# ListenPort=10050'
       replace: 'ListenPort=10051'
    - name: Start Agents
      replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '# StartAgents=3'
       replace: 'StartAgents=5'
    - name: Zarejestruj HostName
      command: hostname
      register: nazwa
    - name: Dodanie hostname
      replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: 'Hostname=Zabbix server'
       replace: 'Hostname={{ nazwa.stdout }}'
    - name: Odblokowanie portu
      firewalld:
       port: 10051/tcp
       permanent: yes
       state: enabled
    - name: Przeładuj firewall
      systemd:
       name: firewalld
       state: reloaded
    - name: Uruchom Zabbix Agenta
      service: name=zabbix-agent state=started enabled=yes
    - name: Restart Servera
      reboot:

