- name: Uaktualnienie bufora narzędzia apt-get.
  apt:
    update_cache: yes

- name: Instalacja PHP.
  apt:
    name: php

- name: Instalacja Apache.
  apt:
    name: apache2

- name: Pobranie kodu z repozytorium.
  git: repo=https://github.com/brikis98/php-app.git dest=/var/www/html/app

- name: Uruchomienie serwera Apache.
  service: name=apache2 state=started enabled=yes