---
- hosts: all
  become: true
  tasks:
    - name: Instalacja Zabbix Agenta
      dnf:
        name: https://repo.zabbix.com/zabbix/6.5/centos/9/x86_64/zabbix-agent-7.0.0-alpha3.release1.el9.x86_64.rpm
        state: present
        disable_gpg_check: yes
    - name: Dodanie EnableRemoteCommands
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'EnableRemoteCommands=0'
        replace: '#EnableRemoteCommands=0'
    - name: Zmiana IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server=192.168.168.145'
    - name: Zmiana Portu
      replace:
         path: /etc/zabbix/zabbix_agentd.conf
         regexp: '# ListenPort=10050'
         replace: 'ListenPort=10051'
    - name: Zmiana StartAgents
      replace:
         path: /etc/zabbix/zabbix_agentd.conf
         regexp: '# StartAgents=3'
         replace: 'StartAgents=5'
    - name: Zarejestruj hostname
      command: hostname
      register: nazwa
    - name: Dodanie hostname
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Hostname=Zabbix server'
        replace: 'Hostname={{ nazwa.stdout }}'
    - name: Odblokowanie portu
      firewalld:
        port: 10051/tcp
        pernament: yes
        state: enabled
    - name: Przeładuj firewalle
      systemd:
        name: firewalld
        state: reloaded
    - name: Uruchom Zabbix-agent
      systemd:
        service: name=Zabbix-agent state=started enabled=yes
    - name: Restart serwera
      reboot:
